config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :posts do
    member do
      get 'hide' => 'posts#hide'
      get 'unhide' => 'posts#unhide'
    end
  end
  
  resources :training_logs
  resources :resources
  resources :projects
  resources :goals

  root to: 'dashboard#index'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index

  end
end

app/views/dashboard/_links.html.haml
= link_to root_path, class: 'btn btn-primary mr-2', title: 'Home' do
  .fas.fa-home.text-white-50
= link_to posts_path, class: 'btn btn-primary mr-2', title: 'Work Log' do
  .fas.fa-clipboard-list.text-white-50
= link_to training_logs_path, class: 'btn btn-primary mr-2', title: 'Learning Log' do
  .far.fa-lightbulb.text-white-50
= link_to resources_path, class: 'btn btn-primary mr-2', title: 'Resources' do
  .fas.fa-book-open.text-white-50
= link_to projects_path, class: 'btn btn-primary mr-2', title: 'Projects' do
  .fas.fa-paint-brush.text-white-50
= link_to goals_path, class: 'btn btn-primary mr-2', title: 'Goals' do
  .fas.fa-football-ball.text-white-50

app/views/dashboard/index.html.haml
.container-fluid
  .sign-out
    = link_to 'Sign out', destroy_user_session_path, method: :delete
  .bg-container
    %h1 Emily's Site
    .widgets_container
      = link_to posts_path do
        .dashboard_link
          .fas.fa-clipboard-list.mr-2
          Work Log
      = link_to training_logs_path do
        .dashboard_link
          .far.fa-lightbulb.mr-2
          Learning Log
      = link_to resources_path do
        .dashboard_link
          .fas.fa-book-open.mr-2
          Resources
      = link_to projects_path do
        .dashboard_link
          .fas.fa-paint-brush.mr-2
          Projects