config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :posts do
    member do
      get 'hide' => 'posts#hide'
      get 'unhide' => 'posts#unhide'
    end
  end
  
  resources :training_logs
  resources :resources
  resources :projects
  resources :goals

  root to: 'dashboard#index'
end

app/views/resources/_form.html.haml
= simple_form_for @resource do |f|
  = f.input :name
  = f.input :link
  = f.input :image, as: :file
  = f.submit 'Save Resource', class: 'btn btn-primary'

app/views/resources/edit.html.haml
.container
  %h1 Edit Resource
  = render 'form'

  = link_to 'Back', resources_path

app/views/resources/index.html.haml
.container
  %h1 Resources
  .links
    = render partial: 'dashboard/links'
  .button-container
    - if can?(:manage, Resource)
      = link_to new_resource_path, class: 'btn btn-primary' do
        %i.fas.fa-plus.text-white-50.mr-1
        New resource

  %table.table-bordered.mt-5{width: '100%'}
    %thead
      %tr
        %th Name
        %th Link
        %th Image
        %th
    %tbody
      - @resources.each do |resource|
        %tr
          %td= link_to resource.name, resource_path(resource)
          %td= markdown(resource.link)
          - if resource.image.present?
            %td{width: '40%'}= image_tag resource.image.url(:small)
          - else
            %td{width: '40%'}
          %td{width: '10%'}
            - if can?(:manage, Resource)
              = link_to edit_resource_path(resource) do
                .fas.fa-edit
              = link_to resource_path(resource), method: :delete, data: {confirm: 'Are you sure?'} do
                .fas.fa-trash.ml-4

app/views/resources/new.html.haml
.container
  %h1 Add New Resource
  = render 'form'
  = link_to 'Back', resources_path

app/views/resources/show.html.haml
.container
  %h1= @resource.name
  .multi-button-container
    = link_to resources_path, class: 'btn btn-primary' do
      %i.fas.fa-arrow-left.text-white-50.mr-1

  .card.p-5
    - if @resource.link.present?
      %p Link: #{markdown(@resource.link)}

    - if @resource.image.present?
      %p= image_tag @resource.image.url(:small)