config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :posts do
    member do
      get 'hide' => 'posts#hide'
      get 'unhide' => 'posts#unhide'
    end
  end
  
  resources :training_logs
  resources :resources
  resources :projects
  resources :goals

  root to: 'dashboard#index'
end

app/models/TrainingLog.rb
class TrainingLog
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String
  field :description, type: String
  field :skills, type: String
  field :date, type: Date, default: Date.today
  field :links, type: String
end

app/controllers/training_logs_controller.rb
class TrainingLogsController < ApplicationController

  def index
    @training_logs = TrainingLog.all
  end

  def new
    @training_log = TrainingLog.new
  end

  def create
    @training_log = TrainingLog.create(training_log_params)
    if @training_log.save
      redirect_to training_logs_path, notice: 'Training log successfully created.'
    else
      flash.now.alert = 'Unable to create training log, please check the details and try again.'
      render :new
    end
  end

  def edit
    @training_log = TrainingLog.find(params[:id])
  end

  def update
    @training_log = TrainingLog.find(params[:id])
    if @training_log.update(training_log_params)
      redirect_to training_logs_path, notice: 'Training log successfully updated.'
    else
      flash.now.alert = 'Unable to update training log, please check the details and try again.'
      render :edit
    end
  end

  def destroy
    @training_log = TrainingLog.find(params[:id])
    @training_log.destroy
  end

  private

  def training_log_params
    params.require(:training_log).permit(:title, :description, :skills, :date, :links)
  end
end

app/views/training_logs/_form.html.haml
= simple_form_for @training_log do |f|
  = f.input :title
  = f.input :description, as: :text, input_html: {rows: 5}
  = f.input :skills, as: :text, input_html: {rows: 3}
  = f.input :date, as: :date, html5: true
  = f.input :links, as: :string
  = f.submit 'Save Log', class: 'btn btn-primary'

app/views/training_logs/edit.html.haml
.container
  %h1 Edit Learning Log Entry
  = render 'form'

  = link_to 'Back', training_logs_path

app/views/training_logs/index.html.haml
.container
  %h1 Learning Log
  .links
    = render partial: 'dashboard/links'
  .button-container
    - if can?(:manage, TrainingLog)
      = link_to new_training_log_path, class: 'btn btn-primary' do
        %i.fas.fa-plus.text-white-50.mr-1
        New learning log entry
  %table.table-bordered.table-responsive
    %thead
      %tr
        %th Date
        %th Title
        %th Description
        %th Skills
        %th Links
        %th
    %tbody
      - @training_logs.reverse.each do |log|
        %tr
          %td= log.date.strftime('%d %b %Y')
          %td{width: '15%'}= log.title
          %td{width: '40%'}= markdown(log.description)
          %td.p-0{width: '20%'}= markdown(log.skills)
          %td= markdown(log.links)
          %td{width: '10%'}
            - if can?(:manage, TrainingLog)
              = link_to edit_training_log_path(log) do
                .fas.fa-edit
              = link_to training_log_path(log), method: :delete, data: {confirm: 'Are you sure?'} do
                .fas.fa-trash.ml-4
  

app/views/training_logs/new.html.haml
.container
  %h1 New Learning Log Entry
  = render 'form'
  = link_to 'Back', training_logs_path