config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :posts do
    member do
      get 'hide' => 'posts#hide'
      get 'unhide' => 'posts#unhide'
    end
  end
  
  resources :training_logs
  resources :resources
  resources :projects
  resources :goals

  root to: 'dashboard#index'
end

app/models/Post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip

  field :title
  field :body
  field :hidden, type: Boolean, default: false

  has_mongoid_attached_file :image,
    :styles => {
      :original => ['1920x1680>', :jpg],
      :small    => ['100x100#',   :jpg],
      :medium   => ['250x250',    :jpg],
      :large    => ['500x500>',   :jpg]
    }

  validates_attachment_content_type :image, content_type: /image/
  
  validates_presence_of :title
  validates_presence_of :body

  def hidden?
    hidden
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      redirect_to posts_path, notice: 'Post successfully created.'
    else
      flash.now.alert = 'Unable to create post, please check the details and try again.'
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path, notice: 'Post successfully updated.'
    else
      flash.now.alert = 'Unable to update post, please check the details and try again.'
      render :edit
    end
  end

  def hide
    @post = Post.find(params[:id])
    @post.hidden = true
    @post.save
    redirect_to posts_path
  end

   def unhide
    @post = Post.find(params[:id])
    @post.hidden = false
    @post.save
    redirect_to posts_path
  end

  def show
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image, :hidden)
  end
end

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
  = f.input :title
  = f.input :body, as: :text, input_html: {rows: 10}
  = f.input :image, as: :file
  = f.submit 'Save Post', class: 'btn btn-primary'

app/views/posts/edit.html.haml
.container
  %h1 Edit Post
  = render 'form'

  = link_to 'Back', posts_path

app/views/posts/index.html.haml
.container
  %h1 My Work Log
  .links
    = render partial: 'dashboard/links'
  .button-container
    - if can?(:manage, Post)
      = link_to new_post_path, class: 'btn btn-primary' do
        %i.fas.fa-plus.text-white-50.mr-1
        New post
  - @posts.reverse.each do |post|
    - unless !current_user.admin? && post.hidden?
      .card
        .card-header.title
          = post.title
          .small 
            = post.created_at.strftime('%d %B %Y, %H:%M')
            - if current_user.admin?
              - if post.hidden?
                = link_to unhide_post_path(post), method: :get, title: 'Show post' do
                  %i.hide-button.fas.fa-eye-slash.ml-4
              - else
                = link_to hide_post_path(post), method: :get, title: 'Hide post' do
                  %i.hide-button.fas.fa-eye.ml-4
        .card-body
          - unless post.body.nil?
            = markdown(post.body)
          - if post.image.present?
            = image_tag post.image.url(:small)
        - if can?(:manage, Post)
          .actions.text-right
            = link_to new_training_log_path do
              %i.fas.fa-lightbulb.mr-1
            = link_to edit_post_path(post) do
              %i.fas.fa-edit
            = link_to post_path(post), method: :delete, data: { confirm: 'Are you sure?' } do
              %i.fas.fa-trash.mr-3
      %br/

app/views/posts/new.html.haml
.container
  %h1 Today's Post
  = render 'form'
  = link_to 'Back', posts_path